Update documentation
IntelPython/numba-dppy pull request #232
Opened 2021-02-02 22:40 UTC by reazulhoque

This should potentially update the Documentation with all the NumPy function we support. 

@PokhodenkoSA is there a way to preview the changes before we merge it?

2021-02-03 00:14 UTC, diptorupd commented
>  is there a way to preview the changes before we merge it?

I suggest hosting the generated pages under your personal github.io page. It will be really useful to review by looking at the resulting documentation.

2021-02-04 16:23 UTC, reazulhoque commented
Preview: https://reazulhoque.github.io/numba-dppy/latest/index.html

2021-02-05 14:49 UTC, diptorupd commented
> 
> 
> Preview: https://reazulhoque.github.io/numba-dppy/latest/index.html

@reazulhoque following up from out conversation from yesterday, it would be great to have a table for the functions that Numba supports on CPU and what we support for XPU.

2021-11-19 09:23 UTC, PokhodenkoSA requested changes
Please remove temporary files.

2021-11-19 09:23 UTC, PokhodenkoSA commented on dev/_static/documentation_options.js
> +    VERSION: '0+untagged.655.g2343fe5',
Why this files and others from `dev` folder are committed?

2021-12-03 20:41 UTC, PokhodenkoSA commented
@reazulhoque as I know we have automatic documentation generation - #547. So it is better to make PR for changing documentation sources rather than generated documentation.

2021-12-03 20:47 UTC, closed without merging