Auto docs generation for gh-pages
IntelPython/numba-dppy pull request #286
Opened 2021-03-12 17:26 UTC by vlad-perevezentsev

The documentation is generated in the` gh-pages` branch in different folders depending on different events:

- push to the `main` branch ----> to the `dev` folder

- push to the `release*` branch ----> to the `next_release` folder

- create tags for a release ----> to the `tag_name` folder

2021-03-29 14:00 UTC, PokhodenkoSA requested changes

2021-03-29 14:00 UTC, PokhodenkoSA commented on scripts/install_dpctl.sh
> +conda build conda-recipe/ --no-test -c ${ONEAPI_ROOT}/conda_channel
Here you build with packages from oneAPI. Why did not you use numba from this channel too?

2021-04-01 09:58 UTC, PokhodenkoSA commented on .github/workflows/build-sphinx.yml
> +      - '[0-9].+**'
Please find a better regexp to match tags.

2021-04-01 12:23 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +        uses: styfle/cancel-workflow-action@0.6.0
I used this workflow during testing. I will delete it, thank you .

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +      - name: Update libstdc++-dev
Great question!
This is really not necessary.

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +                               intel-oneapi-mkl-devel          \
You are right. I will delete it.

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +      # https://github.com/marketplace/actions/checkout
Ok. I will delete this line

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +        uses: conda-incubator/setup-miniconda@v2
There are difficulties in using the default conda in github actions. It is better to install a сonda to escape all difficulties.

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +          python setup.py develop
Intel channel has version 0.51.2 which is not compatible with numba-dppy.

2021-04-01 12:24 UTC, vlad-perevezentsev commented on .github/workflows/build-sphinx.yml
> +          ./0.builddoc.sh
You are right. I will fix it.

2021-04-01 12:24 UTC, vlad-perevezentsev commented on scripts/install_dpctl.sh
> +DPCTL_TARGET_VERSION=0.5.0rc2
I will remove this script. Dpctl will be installed from the intel channel with version 0.3.8

2021-04-06 08:04 UTC, vlad-perevezentsev commented
Required changes:
1. Use cash to install OneApi
2. Correct use of conda.
3. Better pattern for tags.

2021-09-20 14:59 UTC, closed without merging