Add check to remove dead code only when function name is replaced
IntelPython/numba-dppy pull request #303
Opened 2021-03-31 20:59 UTC by reazulhoque

This PR makes sure we try to remove dead code only when we replace the Numpy function names with our own. Removing dead code regardless was failing in cases where we have multiple `prange` as mentioned in [this issue](https://github.com/IntelPython/numba-dppy/issues/302). This PR should close https://github.com/IntelPython/numba-dppy/issues/302.

2021-04-05 10:46 UTC, PokhodenkoSA requested changes
Please, provide test case.

2021-04-05 16:09 UTC, reazulhoque commented
@PokhodenkoSA this bug was noticed originally because [this test](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/tests/test_prange.py) was falling back. This PR fixes this test from falling back and offloads it through our pipeline. Should we ask the original author of that test to make sure it fails if it is falling back instead of going through our pipeline?

I can always write tests and that would require setting up a partial compiler pipeline to test it, which is tedious. Please share your thoughts.

2021-04-06 07:53 UTC, PokhodenkoSA commented
> [this test](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/tests/test_prange.py) was falling back.

Does it mean that test did not check that code falling back? So test was blind?
No when you fix the code did you fix the test to check that fallback is not happening now?
I think test should be fixed first to catch bad situation and show that the test fails. Then your fix for the feature should show that it makes test passing.

2021-04-27 14:16 UTC, reazulhoque commented
>> Does it mean that test did not check that code falling back? So test was blind?
Yes.

I have updated the tests to check for falling back.

2021-04-27 18:36 UTC, PokhodenkoSA commented on numba_dppy/tests/test_prange.py
> +        self.assertTrue("Parfor lowered to specified SYCL device" in stdout.getvalue())
```suggestion
        self.assertIn("Parfor lowered to specified SYCL device", stdout.getvalue())
```

2021-04-27 18:38 UTC, PokhodenkoSA commented on numba_dppy/tests/test_prange.py
> +            stdout.getvalue().count(""),
```suggestion
            stdout.getvalue().count("Parfor lowered to specified SYCL device"),
```

2021-04-30 18:28 UTC, PokhodenkoSA commented on numba_dppy/tests/test_prange.py
> +        with assert_auto_offloading(1, 0), dpctl.device_context("opencl:gpu"):
```suggestion
        with assert_auto_offloading(parfors=1, 0), dpctl.device_context("opencl:gpu"):
```

2021-04-30 18:28 UTC, PokhodenkoSA commented on numba_dppy/testing.py
> +    expected_offloaded_count=-1, expected_not_offloaded_count=-1
```suggestion
    parfors=-1, expected_not_offloaded_count=-1
```

2021-04-30 18:43 UTC, PokhodenkoSA commented on numba_dppy/testing.py
> +    expected_offloaded_count=-1, expected_not_offloaded_count=-1
We could find better name for parameters.

2021-04-30 18:43 UTC, PokhodenkoSA commented on numba_dppy/tests/test_prange.py
> +        with assert_auto_offloading(1, 0), dpctl.device_context("opencl:gpu"):
Use keyword arguments.

2021-04-30 18:46 UTC, PokhodenkoSA commented on numba_dppy/testing.py
> +    expected_offloaded_count=-1, expected_not_offloaded_count=-1
Use 0 as default value for the second parameter.

2021-04-30 18:47 UTC, PokhodenkoSA commented on numba_dppy/testing.py
> +
Reset DEBUG to old value.

2021-05-17 20:03 UTC, reazulhoque commented
@PokhodenkoSA @diptorupd Can you please review it?

2021-05-18 09:50 UTC, PokhodenkoSA approved these changes

2021-05-18 09:54 UTC, merged