Rename dppl to dppy
IntelPython/numba-dppy pull request #42
Opened 2020-12-03 11:14 UTC by 1e-to

Closes the issue https://github.com/IntelPython/numba-dppy/issues/8

Files in which it was not possible to rename, due to connection with dpCtl:

- numba_dppy/dppy_host_fn_call_gen.py
- numba_dppy/experimental_numpy_lowering_overload.py
- numba_dppy/initialize.py

Locally tested:
    Ran 140 tests in 28.366s
    OK (skipped=26, expected failures=1)

2020-12-04 08:36 UTC, PokhodenkoSA requested changes
Please, update with main branch. It will fix CI.

2020-12-04 14:07 UTC, 1e-to commented
I'll tested it with https://github.com/IntelPython/dpctl/pull/201

Ran 140 tests in 28.973s
OK (skipped=26, expected failures=1)

dpctl                     0.3.8+100.gba65df7          pypi_0    pypi

2020-12-04 15:35 UTC, diptorupd approved these changes
Apart from minor changes. LGTM!

2020-12-04 15:35 UTC, diptorupd commented on numba_dppy/__init__.py
> +    between the Numba-PyDPPY version and the OpenCL version, the difference is
Maybe `Numba-DPPY` instead of `Numba-PyDPPY`

2020-12-04 15:35 UTC, diptorupd commented on numba_dppy/__init__.py
> +    raise ImportError("Importing dppy failed")
`numba-dppy` instead of `dppy`. Our extension package is called `numba-dppy`.

2020-12-05 03:40 UTC, diptorupd commented
@PokhodenkoSA I have merged master and made couple of changes to let numba-dppy build with dpctl/master. CI needs to be updated to use dpctl master.

2020-12-05 13:28 UTC, PokhodenkoSA commented on conda-recipe/meta.yaml
> +        - cffi
```suggestion
```

2020-12-05 13:29 UTC, PokhodenkoSA commented on setup.py
> +    "cffi",
```suggestion
```

2020-12-05 13:30 UTC, PokhodenkoSA commented on numba_dppy/tests/__init__.py
> +
Clean commented code.

2020-12-05 13:30 UTC, PokhodenkoSA requested changes
It seems that branch is not up tp date with main branch.

2020-12-07 19:44 UTC, PokhodenkoSA approved these changes

2020-12-07 19:44 UTC, merged