Pass correct `linkage_name` attribute to DIBuilder
IntelPython/numba-dppy pull request #434
Opened 2021-06-09 14:39 UTC by vlad-perevezentsev

New file created `dppy_debuginfo.py` with the `DPPYDIBuilder` class.
`DPPYDIBuilder` modifies `mark_subprogram` method and passes  correct name to `linkage_name` attribute.

New `ModifiedLower` class contains the constructor needed to create an instance of `DPPYDIBuilder` class.

2021-06-09 15:02 UTC, PokhodenkoSA requested changes

2021-06-09 15:02 UTC, PokhodenkoSA commented on numba_dppy/dppy_debuginfo.py
> +        if isinstance(name, tuple):
See below. Tuple could be replaced by using `DPPYDIBuilder` member for `mangled_qualname`.

2021-06-09 23:22 UTC, vlad-perevezentsev commented on numba_dppy/dppy_lowerer.py
> +        self.context = context.subtarget(environment=self.env, fndesc=self.fndesc)
I tried this suggestion earlier, but then we create two IR modules:
https://github.com/IntelPython/numba-dppy/pull/434/files#diff-6c8257f1d30d71128472a57b8a7e3e1d791915b259eb6116988b3465ab3f68fbR1231
I do not know if this is correct but breakpoints by function name work.
![image](https://user-images.githubusercontent.com/68376232/121440576-d1f68600-c990-11eb-8fa6-e3e9f4191137.png)
![image](https://user-images.githubusercontent.com/68376232/121440636-f5b9cc00-c990-11eb-81af-822933648b54.png)

2021-06-09 23:22 UTC, vlad-perevezentsev commented on numba_dppy/dppy_lowerer.py
> +from numba import core
Yes. I will delete this line.

2021-06-09 23:22 UTC, vlad-perevezentsev commented on numba_dppy/dppy_debuginfo.py
> +from numba.core.debuginfo import DIBuilder
I will add license.

2021-06-09 23:25 UTC, vlad-perevezentsev commented on numba_dppy/dppy_lowerer.py
> +            self.debuginfo = DPPYDIBuilder(
Is it correct to change the signature of a function in a child class? Should not the signature match the parent class?
https://github.com/IntelPython/numba/blob/release0.53-patched/numba/core/debuginfo.py#L141

2021-06-10 07:57 UTC, PokhodenkoSA commented on numba_dppy/dppy_lowerer.py
> +            self.debuginfo = DPPYDIBuilder(
Yes, if the child class support the additional parameter.

2021-06-10 07:58 UTC, PokhodenkoSA commented on numba_dppy/dppy_debuginfo.py
> +        self.linkage_name = mangled_qualname
```suggestion
    def __init__(self, module, filepath, linkage_name ):
        DIBuilder.__init__(self, module, filepath)
        self.linkage_name = linkage_name 
```

2021-06-10 07:58 UTC, PokhodenkoSA commented on numba_dppy/dppy_debuginfo.py
> +        self.linkage_name = mangled_qualname
no need for new name

2021-06-10 07:59 UTC, PokhodenkoSA commented on numba_dppy/dppy_lowerer.py
> +        self.qualprefix = qualifying_prefix(fndesc.modname, fndesc.qualname)
Used anywhere?

2021-06-14 09:05 UTC, PokhodenkoSA approved these changes
Added tests and code cleanup.

2021-06-14 09:21 UTC, merged