Fix env variables in debug tests
IntelPython/numba-dppy pull request #443
Opened 2021-06-11 13:05 UTC by akharche

Fix env variables in debug tests

2021-06-13 06:52 UTC, PokhodenkoSA commented
I have implemented the same in #432 via `override_config`.

2021-06-13 06:55 UTC, PokhodenkoSA requested changes

2021-06-13 06:55 UTC, PokhodenkoSA commented on numba_dppy/tests/test_debuginfo.py
> +    opt_curr_value = os.environ.get("NUMBA_OPT", 3)  # 3 is a default value
Do not use both `os.environ` and `config`. They do the same from different levels.

2021-06-15 11:28 UTC, akharche commented
Resolved by #432

2021-06-15 11:28 UTC, closed without merging