All Numba-dppy tests and examples using the @njit decorator should be used with "with_context"
IntelPython/numba-dppy pull request #46
Opened 2020-12-03 13:58 UTC by vlad-perevezentsev

https://github.com/IntelPython/numba-dppy/issues/30

Changed one test for the example.

2020-12-03 18:39 UTC, reazulhoque commented
@vlad-perevezentsev The changes are correct, let's change all the programs that need this change.

2020-12-04 09:21 UTC, PokhodenkoSA commented
@vlad-perevezentsev Please, merge with main. It will fix CI.

2020-12-04 15:50 UTC, reazulhoque commented
@vlad-perevezentsev Do you know what is causing the conflicts? Please let us know when the work is complete and we will start reviewing it.

2020-12-07 18:28 UTC, PokhodenkoSA approved these changes
LGTM. Will be merged after CI passes.

2020-12-07 18:35 UTC, reazulhoque approved these changes
LGTM

2020-12-08 13:48 UTC, PokhodenkoSA requested changes
Please, merge with main. Replace `DPPLTestCase` with `DPPYTestCase`. CI fails because of that.

2020-12-08 13:48 UTC, PokhodenkoSA commented on numba_dppy/tests/test_dpnp_functions.py
> +class Testdpnp_functions(DPPLTestCase):
```suggestion
class Testdpnp_functions(DPPYTestCase):
```

2020-12-08 13:48 UTC, PokhodenkoSA commented on numba_dppy/tests/test_numpy_bit_twiddling_functions.py
> +class TestNumpy_bit_twiddling_functions(DPPLTestCase):
```suggestion
class TestNumpy_bit_twiddling_functions(DPPYTestCase):
```

2020-12-09 07:57 UTC, PokhodenkoSA commented on numba_dppy/tests/test_vectorize.py
> +import numba_dppy as dppl
```suggestion
import numba_dppy as dppy
```

2020-12-09 07:59 UTC, PokhodenkoSA commented
Windows fails possibly because Level0 is also available on CI machine and it is used by default.

2020-12-10 18:16 UTC, reazulhoque commented
@vlad-perevezentsev  Please merge main to this PR and please mention the issues this PR is addresseing.

2020-12-11 07:53 UTC, PokhodenkoSA commented
Applied comments from @diptorupd from https://github.com/IntelPython/numba-dppy/issues/65 in this commit https://github.com/IntelPython/numba-dppy/pull/46/commits/b34bb513f72b7be96b062c6b7615e9d92bf14c5d

2020-12-11 12:27 UTC, PokhodenkoSA approved these changes

2020-12-11 12:27 UTC, merged