Enable optimization level setting
IntelPython/numba-dppy pull request #62
Opened 2020-12-10 14:04 UTC by akharche

Issue #39

2020-12-11 14:18 UTC, PokhodenkoSA requested changes
Please, merge with master.

2020-12-11 14:22 UTC, akharche commented
This PR breaks GDB support when -O0 optimization level is set

2021-02-20 13:55 UTC, akharche commented
@reazulhoque @diptorupd  If we take `llvm-spirv` from oneapi compiler, it solves the problem with crash on "-O0" opt level

2021-04-21 02:37 UTC, diptorupd approved these changes

2021-04-26 18:19 UTC, PokhodenkoSA commented on numba_dppy/codegen.py
> +        pmb.opt_level = 0 if opt_level_option == 0 else 1
Why `pmb.opt_level` is not equal to `config.OPT`?

2021-04-27 16:09 UTC, reazulhoque commented
@PokhodenkoSA @diptorupd should we merge this?

2021-04-27 16:34 UTC, akharche commented
@reazulhoque I think, it should be merge after problem with -O0 (addr space casting) is fixed. This code will fail if user changes option NUMBA_OPT to 0

2021-04-28 09:57 UTC, PokhodenkoSA commented
> This code will fail if user changes option NUMBA_OPT to 0

It is up to user to use any NUMBA_OPT value. This PR only provides an option to configure.
If default NUMBA_OPT value is appropriate we could merge this PR.

2021-04-28 09:57 UTC, PokhodenkoSA approved these changes

2021-04-28 18:20 UTC, merged