Fix test "with context"
IntelPython/numba-dppy pull request #646
Opened 2021-11-26 11:28 UTC by 1e-to

Missed check on existing device
Without level-zero:
```python
FAILED numba_dppy/tests/test_with_context.py::test_dpctl_device_context_affects_numba_pipeline[device_context0-level_zero:gpu:0] - V...
FAILED numba_dppy/tests/test_with_context.py::test_dpctl_device_context_affects_numba_pipeline[device_context1-level_zero:gpu:0] - V...
```

2021-11-26 11:43 UTC, PokhodenkoSA requested changes

2021-11-26 11:43 UTC, PokhodenkoSA commented on numba_dppy/tests/test_with_context.py
> +        pytest.skip()
The problem is not here. In line 38 `pytest.param("level_zero:gpu:0", marks=skip_no_gpu)` should be skipped if GPU is not available. So it should be skipped if L0 is not available.

2021-11-29 12:50 UTC, PokhodenkoSA commented on numba_dppy/tests/test_with_context.py
> +    ),
3 indentations. I think it is too much.

2021-11-29 14:53 UTC, 1e-to commented on numba_dppy/tests/test_with_context.py
> +            _helper.skip_test("opencl:gpu:0"),
What about rewriting the skip_test function in such a way that all device checks are included in it (is there a gpu, cpu, opencl, level-zero) and return the message why test fail. And accordingly change the skip to xfail?

2021-11-29 15:04 UTC, PokhodenkoSA commented on numba_dppy/tests/test_with_context.py
> +            _helper.skip_test("opencl:gpu:0"),
> all device checks are included in it

This functions should be named - `check_device`, not `skip_test`.

> and return the message why test fail.

It seems that function will have second responsibility.

I would prefer one function with simple responsibility - return pytest mark for the device.

2021-11-30 10:58 UTC, PokhodenkoSA commented on numba_dppy/tests/test_with_context.py
> +    not _helper.has_gpu_queues("level_zero"),
Please, pass also "opencl" for `skip_no_gpu` to make it obvious.

2021-12-01 08:40 UTC, PokhodenkoSA approved these changes

2021-12-01 08:42 UTC, merged